### ISSUE TITLE
Minor correction for menu

### ISSUE THREAD

**Issue by lonix1** [wraith13/file-path-bar-vscode#5]
Hello @wraith13, thanks for this excellent extension! :smile:

Please note there are two spelling mistakes, [here](https://github.com/wraith13/file-path-bar-vscode/blob/master/source/extension.ts#L96-L97) and [here](https://github.com/wraith13/file-path-bar-vscode/blob/master/source/extension.ts#L121). `Reval` should be `Reveal`.

ありがとう

**Comment by wraith13** [comment]
Thank you for your report.
I fixed it and published.
